### ISSUE TITLE
Argument passed to call that takes no arguments

### ISSUE THREAD

**Issue by leibaozai** [DemoDu/MMLayout-#3]
用swift调用，会出现Argument passed to call that takes no arguments，想问下有什么办法解决吗

**Comment by leibaozai** [comment]
自己对swift语法不熟悉，调用错误
错误调用
view.mm_top(10.0) 会报 Argument passed to call that takes no arguments 
正确调用
view.mm_top()!(10.0)

**Comment by CoderDuMeng** [comment]
使用swift 的类型包装一下 比如 CGFloat(10)
